name: Build and deploy prenoms API

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker build
        run: docker build -t tp .

      - name: Docker login
        run: docker login -u omaraouachri -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker tag
        run: docker tag tp omaraouachri/tp:${{ github.sha }}

      - name: Docker push
        run: docker push omaraouachri/tp:${{ github.sha }}



      - name: Auth GCP gcloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Check if Compute Instance 'prenoms-api-omar' exists
        id: check
        run: echo "INSTANCE_EXISTS=$(gcloud compute instances list | grep prenoms-api-omar | wc -l | xargs)" >> "$GITHUB_OUTPUT"

      - name: Debug check value
        run: echo '${{ steps.check.outputs.INSTANCE_EXISTS }}'

      - name: Create (for the first time) API to GCP Compute Instance
        if: steps.check.outputs.INSTANCE_EXISTS == '0'
        run: |
          gcloud compute instances create-with-container prenoms-api-omar \
            --container-image omaraouachri/tp:${{ github.sha }} \
            --tags http-server \
            --zone asia-east1-a \
            --container-env FLASK_PORT=80

      - name: Update API to GCP Compute Instance
        if: steps.check.outputs.INSTANCE_EXISTS != '0'
        run: |
          gcloud compute instances update-container prenoms-api-omar \
            --container-image omaraouachri/tp:${{ github.sha }} \
            --zone asia-east1-a \
            --container-env FLASK_PORT=80 